# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'translate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ENtoZH(object):
    def setupUi(self, ENtoZH):
        ENtoZH.setObjectName("ENtoZH")
        ENtoZH.resize(514, 129)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ENtoZH)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 451, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.textBrowser = QtWidgets.QTextBrowser(ENtoZH)
        self.textBrowser.setGeometry(QtCore.QRect(40, 70, 371, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(ENtoZH)
        self.label.setGeometry(QtCore.QRect(440, 60, 47, 13))
        self.label.setObjectName("label")
        self.textBrowser_2 = QtWidgets.QTextBrowser(ENtoZH)
        self.textBrowser_2.setGeometry(QtCore.QRect(430, 80, 51, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.retranslateUi(ENtoZH)
        QtCore.QMetaObject.connectSlotsByName(ENtoZH)

    def retranslateUi(self, ENtoZH):
        _translate = QtCore.QCoreApplication.translate
        ENtoZH.setWindowTitle(_translate("ENtoZH", "Translator"))
        self.pushButton.setText(_translate("ENtoZH", "Translate"))
        self.label.setText(_translate("ENtoZH", "Time"))
